"""Add ON DELETE CASCADES's

Revision ID: 0c2a942cdd6b
Revises: 2851ebe8e028
Create Date: 2019-01-12 19:04:20.955509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2a942cdd6b'
down_revision = '2851ebe8e028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_ibfk_1', 'price', type_='foreignkey')
    op.drop_constraint('price_ibfk_2', 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'price', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('productTag_ibfk_1', 'productTag', type_='foreignkey')
    op.create_foreign_key(None, 'productTag', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shopTag_ibfk_1', 'shopTag', type_='foreignkey')
    op.create_foreign_key(None, 'shopTag', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopTag', type_='foreignkey')
    op.create_foreign_key('shopTag_ibfk_1', 'shopTag', 'shop', ['shop_id'], ['id'])
    op.drop_constraint(None, 'productTag', type_='foreignkey')
    op.create_foreign_key('productTag_ibfk_1', 'productTag', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key('price_ibfk_2', 'price', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key('price_ibfk_1', 'price', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
