"""empty message

Revision ID: 6c6165f1ac56
Revises: fcb5903a81ab
Create Date: 2019-01-12 04:03:32.005151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6165f1ac56'
down_revision = 'fcb5903a81ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'address')
    # ### end Alembic commands ###
