"""Add unique constraints

Revision ID: b552e04f530f
Revises: e9c7eb1f3619
Create Date: 2019-01-31 14:33:51.664204

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b552e04f530f'
down_revision = 'e9c7eb1f3619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('price_psd_c', 'price', ['product_id', 'shop_id', 'date'])
    op.create_unique_constraint('productTag_id_name_c', 'productTag', ['product_id', 'name'])
    op.create_unique_constraint('shop_pna_c', 'shop', ['position', 'name', 'address'])
    op.drop_index('idx_shop_position', table_name='shop')
    op.create_unique_constraint('shopTag_id_name_c', 'shopTag', ['shop_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shopTag_id_name_c', 'shopTag', type_='unique')
    op.create_index('idx_shop_position', 'shop', ['position'], unique=False)
    op.drop_constraint('shop_pna_c', 'shop', type_='unique')
    op.drop_constraint('productTag_id_name_c', 'productTag', type_='unique')
    op.drop_constraint('price_psd_c', 'price', type_='unique')
    # ### end Alembic commands ###
