"""empty message

Revision ID: da5e64547ef2
Revises: 
Create Date: 2019-01-12 03:45:23.026494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da5e64547ef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopTag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('product', 'tags')
    op.add_column('shop', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('shop', sa.Column('lng', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'lng')
    op.drop_column('shop', 'lat')
    op.add_column('product', sa.Column('tags', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_table('shopTag')
    # ### end Alembic commands ###
