"""empty message

Revision ID: fcb5903a81ab
Revises: da5e64547ef2
Create Date: 2019-01-12 03:49:44.515638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb5903a81ab'
down_revision = 'da5e64547ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('withdrawn', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'withdrawn')
    # ### end Alembic commands ###
